name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1    
  smooth_page_indicator: ^1.1.0
  http: ^1.1.0
  cached_network_image: ^3.3.1
  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - images/business.jpg
  - images/entertainment.jpeg
  - images/general.jpg
  - images/health.jpeg
  - images/science.jpeg
  - images/sport.jpg
  - images/landing.jpeg
  - images/placeholder.png
